Feature/number of requests chart
apinf/api-umbrella-dashboard pull request #4
Opened 2017-06-13 09:20 UTC by brylie

Closes #3

2017-06-14 12:04 UTC, brylie commented
ping @marla-singer

2017-06-14 12:22 UTC, marla-singer requested changes

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      return d3.time.format('%x')(new Date(d))
Replace anonymous function to an arrow-function. Make compact function like
```js
.tickFormat( d => d3.time.format('%x')(new Date(d) )
```

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +  templateInstance.autorun(function () {
Replace to arrow-function

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      Meteor.call('getElasticsearchData', elasticsearchHost, queryParams, function (error, result) {
Replace to an arrow-function

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      const elasticsearchAggregation = elasticsearchData.aggregations.requests_over_time.buckets;
As for me `aggregatedData` name of variable will be more meaning for this case

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      console.log(elasticsearchAggregation);
Remove console.log

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      console.log(chartData);
Remove console.log

2017-06-14 12:22 UTC, marla-singer commented on main/server/methods/elasticsearch.js
> +      console.log(elasticsearchData);
Remove console.log

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      const chartDataValues = _.map(elasticsearchAggregation, function (datum) {
We can escape redundant loop if you will use methods of library properly. 
You must write above:

```js
// Initialize chart
  const chart = nvd3.models.historicalBar();

// configure chart
chart
  .x(d => d.key)
  .y(d => d.doc_count)
  .xScale(d3.time.scale())

...


```

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/dashboard.html
> +
Remove needless an empty line

2017-06-14 12:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.html
> +
Remove needless an empty line

2017-06-14 13:04 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.js
> +      return d3.time.format('%x')(new Date(d))
This code does not need to inherit `this` from the parent context, so an arrow function is not necessary.

2017-06-14 13:04 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.js
> +  templateInstance.autorun(function () {
This code does not need to inherit this from the parent context, so an arrow function is not necessary.

2017-06-14 13:04 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.js
> +      Meteor.call('getElasticsearchData', elasticsearchHost, queryParams, function (error, result) {
This code does not need to inherit this from the parent context, so an arrow function is not necessary.

2017-06-14 13:11 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.html
> +
In this case, the blank line separates two block elements. Leaving a blank line between blocks improves readability. This is similar to how we leave blank lines between statements in our codebase.

2017-06-14 13:11 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.html
> +
We can think of the blank line here as a paragraph break.

2017-06-14 13:22 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +      Meteor.call('getElasticsearchData', elasticsearchHost, queryParams, function (error, result) {
In the main project we have a special rule that says "prefer arrow-function"
As I understand code from this repo will move to main then please follow it

2017-06-14 13:23 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.js
> +      Meteor.call('getElasticsearchData', elasticsearchHost, queryParams, function (error, result) {
I did.

2017-06-14 13:41 UTC, marla-singer commented on dashboard/client/requests_over_time/requests_over_time.js
> +        .datum(chartData)
In the future we will need to regulate the size of a chart. To keep it in mind let's create two variables: width and height for canvas chart, and provide them as
```js
d3.select('#requests-over-time-chart svg')
 .attr('width', width)
 .attr('height', height)
  .datum(chartData)
...
```

2017-06-15 12:15 UTC, marla-singer approved these changes

2017-06-15 12:15 UTC, merged

2017-06-15 12:26 UTC, brylie commented on dashboard/client/requests_over_time/requests_over_time.js
> +        .datum(chartData)
Can we work on the chart size in a different PR? I would like to continue working on the wireframes, and we might need to adjust the chart sizes once we have more template structure in place.